name: roc_droid
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localization: ^0.2.0
  intl: any
  logger: ^2.4.0
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1
  darq: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  test: ^1.25.2
  build_runner: ^2.4.11
  mobx_codegen: ^2.6.1

flutter:
  uses-material-design: true
  generate: true
